# Generated by Django 2.0.2 on 2018-03-05 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(unique=True, verbose_name='url')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '북마크',
                'ordering': ['title'],
                'verbose_name_plural': '북마크 모음',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Member',
            },
        ),
    ]
